export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const CHANGE_VIEW = "CHANGE_VIEW"
export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT"
export const EDIT_ANNOUNCEMENT_FORM = "EDIT_ANNOUNCEMENT_FORM"
export const CLEAR_ANNOUNCEMENT_FORM = "CLEAR_ANNOUNCEMENT_FORM"
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT"

