export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const CHANGE_VIEW = "CHANGE_VIEW"
export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT"
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT"
export const INC_ANNOUNCEMENT_FIELD = "INC_ANNOUNCEMENT_FIELD"
export const EDIT_ANNOUNCEMENT_FORM = "EDIT_ANNOUNCEMENT_FORM"
export const CLEAR_ANNOUNCEMENT_FORM = "CLEAR_ANNOUNCEMENT_FORM"
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT"
export const UPDATE_COMMENT_FORM = "UPDATE_COMMENT_FORM"


